# Generated by Django 3.2 on 2021-12-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id_juego', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_juego', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('G', 'Grupal'), ('I', 'Individual'), ('R', 'ROL')], default='G', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Jugadore',
            fields=[
                ('id_jugador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_jugador', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('edad', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
