# Generated by Django 3.2 on 2021-12-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades_ludicas', '0003_alter_jugadore_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadore',
            name='juegos',
            field=models.ManyToManyField(to='actividades_ludicas.Juego'),
        ),
    ]
